version: "3.8"

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    #   MONGO_INITDB_DATABASE: test
    networks:
      - local

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   # environment:
  #   #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #   #   ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #   #   ME_CONFIG_MONGODB_SERVER: mongo-db

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    networks:
      - local

networks:
  local:
    driver: bridge
